version: '3'

services:
  mongodb:
    image: mongo:3-xenial
    container_name: mongodb
    volumes:
      - ./mongodb/init-db.js:/docker-entrypoint-initdb.d/init-db.js
    expose:
      - "27017"
    networks:
      - category
      - product
  category:
    build:
      context: ./category
    image: category:latest
    container_name: category
    depends_on:
      - mongodb
    links:
      - mongodb
    expose:
      - "8081"
    networks:
      - category
      - integration_category
  product:
    build: 
      context: ./product
      dockerfile: src/main/docker/Dockerfile.jvm
    image: product:latest
    container_name: product
    depends_on:
      - mongodb
    links:
      - mongodb
    expose:
      - "8080"
    networks:
      - product
      - integration_product
  integration:
    build:
      context: ./integration
      dockerfile: src/main/docker/Dockerfile.jvm
    image: integration:latest
    container_name: integration    
    ports:
      - "80:8081"
    depends_on: 
      - product
      - category
    links: 
      - product
      - category
    networks:
      - integration_category
      - integration_product

networks:
  product:
    driver: bridge
  category:
    driver: bridge
  integration_product:
    driver: bridge
  integration_category:
    driver: bridge