version: '3'

services:
  mongodb:
    image: mongo:3-xenial
    container_name: mongodb
    volumes:
      - /mongodb/init-db.js:/docker-entrypoint-initdb.d/init-db.js
  category:
    build: ./category
    image: category:latest
    container_name: category
    depends_on: mongodb
    links: mongodb